language: python
python:
  - "3.3"
  - "2.7"
install: pip install -r requirements.txt
before_script: pep8 .
script:
  - python setup.py test
  - (cd tests/end2end; PYTHONPATH=../.. python manage.py test)
